version: "3.8"

services:
    umbraco-db:
      image: mcr.microsoft.com/mssql/server:latest
      user: root
      env_file: ./configs/ms.sql.env
      volumes:
        - umbraco.db:/var/opt/mssql/data
      restart: always
      ports:
        - '3930:1433'
        - '3931:1434'
    
    umbraco:
      restart: always
      depends_on:
        - umbraco-db
      build:
        context: .
        dockerfile: Dockerfile
      entrypoint: ["./wait-for-it.sh", "host.docker.internal:3930", "-t", "120", "--", "dotnet", "Web.Umbraco.dll"]
      ports:
        - "8080:80"
      volumes: 
        - umbraco.media:/app/wwwroot/media
        - ./src/Web.Umbraco/Views:/app/Views
  
volumes:
    umbraco.db:
    umbraco.media: